fix: missing doc attribute
According to change introduced in [astroid 3.0.0 release notes](https://pylint.readthedocs.io/projects/astroid/en/stable/changelog.html#what-s-new-in-astroid-3-0-0):

- Remove deprecated doc attribute for Module, ClassDef, and FunctionDef. Use the doc_node attribute instead.

This fix should solve following error:

```
AttributeError: 'Module' object has no attribute 'doc'
```