fix: missing global configuration
According to change introduced in [Pylint 3.0.0 release notes](https://pylint.readthedocs.io/en/stable/whatsnew/3/3.0/index.html#internal-changes):

- get_global_option: Use checker.linter.config to get all global options

This fix should solve following error:

```
AttributeError: 'StringQuoteChecker' object has no attribute 'config'
```